/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JankenGui;

/**
 *
 * @author fujil
 */
import javax.swing.ImageIcon;
import java.util.Random;
public class Janken extends javax.swing.JFrame {
    ImageIcon imageRock = new ImageIcon("rock.png");
    ImageIcon imageScissors = new ImageIcon("scissors.png");
    ImageIcon imagePaper = new ImageIcon("paper.png");
    ImageIcon imageQuestionMark = new ImageIcon("question.png");
    int userScore = 0;
    int computerScore = 0;
    
    /**
     * Creates new form Janken
     */
    public Janken() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1UserSelect = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2UserHand = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3ComputerHand = new javax.swing.JLabel();
        jButton1Start = new javax.swing.JButton();
        jLabel2ComputerImage = new javax.swing.JLabel();
        jLabel3UserImage = new javax.swing.JLabel();
        jLabel2UserScore = new javax.swing.JLabel();
        jLabel3ComputerScore = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1ResetScore = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3UserName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1UserSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "Rock", "Paper", "Scissors" }));
        jComboBox1UserSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1UserSelectActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1UserSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("JANKEN GAME ");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 6, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(jLabel2UserHand)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel2UserHand, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 108, 240, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(jLabel3ComputerHand)
                .addGap(31, 31, 31))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel3ComputerHand, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 240, -1));

        jButton1Start.setBackground(new java.awt.Color(105, 176, 105));
        jButton1Start.setText("START");
        jButton1Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1StartActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 90, 38));

        jLabel2ComputerImage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2ComputerImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2ComputerImage.setText("-Select-");
        jPanel1.add(jLabel2ComputerImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 90, -1));

        jLabel3UserImage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3UserImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3UserImage.setText("-Select-");
        jPanel1.add(jLabel3UserImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 96, -1));

        jLabel2UserScore.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2UserScore.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2UserScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2UserScore.setText("0");
        jPanel1.add(jLabel2UserScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 37, -1));

        jLabel3ComputerScore.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3ComputerScore.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3ComputerScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3ComputerScore.setText("0");
        jPanel1.add(jLabel3ComputerScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 37, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 37, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 142, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RESULT");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 389, 550, -1));

        jButton1ResetScore.setBackground(new java.awt.Color(255, 153, 153));
        jButton1ResetScore.setText("Reset Score");
        jButton1ResetScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ResetScoreActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1ResetScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Score:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jLabel3UserName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3UserName.setText("User");
        jPanel1.add(jLabel3UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Computer");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 740, 500));

        setSize(new java.awt.Dimension(768, 521));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1UserSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1UserSelectActionPerformed
        
        String comboBoxSelectedHand = jComboBox1UserSelect.getSelectedItem().toString();
        userHandSelector(comboBoxSelectedHand);
    }//GEN-LAST:event_jComboBox1UserSelectActionPerformed
    
    private void jButton1StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1StartActionPerformed
        
        computerHandSelector(generateComputerHand());
        resultWinner();
    }//GEN-LAST:event_jButton1StartActionPerformed

    private void jButton1ResetScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ResetScoreActionPerformed
        resetScore();
    }//GEN-LAST:event_jButton1ResetScoreActionPerformed
    
    private void userHandSelector(String userHand){
        
        if (userHand == "Rock"){
            jLabel2UserHand.setIcon(imageRock);
            jLabel3UserImage.setText(userHand);
        }
        else if (userHand == "Scissors"){
            jLabel2UserHand.setIcon(imageScissors);
            jLabel3UserImage.setText(userHand);
        }
        else if (userHand == "Paper"){
            jLabel2UserHand.setIcon(imagePaper);
            jLabel3UserImage.setText(userHand);
        }
        else if (userHand == "-Select-"){
            jLabel2UserHand.setIcon(imageQuestionMark);
            jLabel3UserImage.setText(userHand);
        }
    }

    private String generateComputerHand(){
        Random random = new Random();
        String randomComputerHand[] = new String[]{"Rock","Scissors","Paper"};
        String finalComputerHand = randomComputerHand[random.nextInt(randomComputerHand.length)];
        return finalComputerHand;
    }
    
    private void computerHandSelector(String computerHand){
        if (computerHand == "Rock"){
            jLabel3ComputerHand.setIcon(imageRock);
            jLabel2ComputerImage.setText("Rock");
        }
        else if (computerHand == "Scissors"){
            jLabel3ComputerHand.setIcon(imageScissors);
            jLabel2ComputerImage.setText("Scissors");
        }
        else if (computerHand == "Paper"){
            jLabel3ComputerHand.setIcon(imagePaper);
            jLabel2ComputerImage.setText("Paper");
        }
        else if (computerHand == "-Select-"){
            jLabel3ComputerHand.setIcon(imageQuestionMark);
            jLabel2ComputerImage.setText("-Select-");
        }
    }
    
    private void resultWinner(){
        String computerHandLabel = jLabel2ComputerImage.getText();
        String userHandLabel = jLabel3UserImage.getText();
        
        if (userHandLabel.compareTo(computerHandLabel)==0){
            jLabel5.setText("TIE!"); 
        }
        else if (userHandLabel.compareTo("Rock")== 0  && computerHandLabel.compareTo("Scissors")== 0) {
            jLabel5.setText("USER WINS!");
            userScore++;
            jLabel2UserScore.setText(Integer.toString(userScore));
        }
        else if (userHandLabel.compareTo("Paper")== 0  && computerHandLabel.compareTo("Rock")== 0) {
            jLabel5.setText("USER WINS!");
            userScore++;
            jLabel2UserScore.setText(Integer.toString(userScore));
        }
        else if (userHandLabel.compareTo("Scissors")== 0  && computerHandLabel.compareTo("Paper")== 0) {
            jLabel5.setText("USER WINS!");
            userScore++;
            jLabel2UserScore.setText(Integer.toString(userScore));
        }
        else if (userHandLabel.compareTo("Paper")== 0  && computerHandLabel.compareTo("Scissors")== 0) {
            jLabel5.setText("COMPUTER WINS!");
            computerScore++;
            jLabel3ComputerScore.setText(Integer.toString(computerScore));
        }
        else if (userHandLabel.compareTo("Scissors")== 0  && computerHandLabel.compareTo("Rock")== 0) {
            jLabel5.setText("COMPUTER WINS!");
            computerScore++;
            jLabel3ComputerScore.setText(Integer.toString(computerScore));
        }
        else if (userHandLabel.compareTo("Rock")== 0  && computerHandLabel.compareTo("Paper")== 0) {
            jLabel5.setText("COMPUTER WINS!");
            computerScore++;
            jLabel3ComputerScore.setText(Integer.toString(computerScore));
        }
        else {
            jLabel5.setText("Please Select User Hand");
        }
    }
    
    private void resetScore(){
        userScore = 0;
        computerScore = 0;
        jLabel3ComputerScore.setText(Integer.toString(computerScore));
        jLabel2UserScore.setText(Integer.toString(userScore));
    }
    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janken().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ResetScore;
    private javax.swing.JButton jButton1Start;
    private javax.swing.JComboBox<String> jComboBox1UserSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2ComputerImage;
    private javax.swing.JLabel jLabel2UserHand;
    private javax.swing.JLabel jLabel2UserScore;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3ComputerHand;
    private javax.swing.JLabel jLabel3ComputerScore;
    private javax.swing.JLabel jLabel3UserImage;
    private javax.swing.JLabel jLabel3UserName;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
